# Generated by Django 5.2.9 on 2026-05-02 12:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_staffprofile_created_at'),
        ('chitti', '0018_alter_chittigroup_auction_interval_months_and_more'),
        ('members', '0005_alter_member_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partial'), ('paid', 'Paid')], default='pending', max_length=20)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chitti.chittigroup')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='members.member')),
            ],
            options={
                'ordering': ['month'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('razorpay', 'Razorpay'), ('cash', 'Cash'), ('upi', 'UPI'), ('bank', 'Bank Transfer')], default='cash', max_length=30)),
                ('payment_status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('pending', 'Pending')], default='success', max_length=20)),
                ('paid_date', models.DateField(default=django.utils.timezone.now)),
                ('paid_time', models.TimeField(auto_now_add=True)),
                ('transaction_id', models.CharField(blank=True, max_length=100, unique=True)),
                ('invoice_number', models.CharField(blank=True, max_length=100, unique=True)),
                ('sent_to_admin', models.BooleanField(default=False)),
                ('received_by_admin', models.BooleanField(default=False)),
                ('admin_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('is_seen', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collected_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.staffprofile')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chitti.chittigroup')),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='members.member')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('installment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.installment')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='payments.payment')),
            ],
        ),
    ]
