# Generated by Django 5.2.9 on 2026-01-10 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='success',
            field=models.BooleanField(default=True),
        ),
    ]
