# Generated by Django 5.2.9 on 2026-01-14 08:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_staffprofile_created_at'),
        ('chitti', '0002_initial'),
        ('payments', '0003_remove_payment_success_payment_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='member',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='month_no',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='pay_type',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='razorpay_order_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='razorpay_payment_id',
        ),
        migrations.AlterField(
            model_name='payment',
            name='collected_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='accounts.staffprofile'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='chitti.chittigroup'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='invoice_number',
            field=models.CharField(blank=True, default=django.utils.timezone.now, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='paid_time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('razorpay', 'Razorpay'), ('cash', 'Cash'), ('upi', 'UPI'), ('bank', 'Bank Transfer')], default='cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, default='UNKNOWN', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
