# Generated by Django 5.2.9 on 2026-01-14 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_staffprofile_created_at'),
        ('chitti', '0002_initial'),
        ('payments', '0004_remove_payment_member_remove_payment_month_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='collected_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.staffprofile'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chitti.chittigroup'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('razorpay', 'Razorpay'), ('cash', 'Cash'), ('upi', 'UPI'), ('bank', 'Bank Transfer')], default='cash', max_length=30),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
