# Generated by Django 5.2.9 on 2026-01-20 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_member_address_and_more'),
        ('payments', '0005_alter_payment_collected_by_alter_payment_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='members.member'),
        ),
    ]
