# Generated by Django 5.2.9 on 2026-01-03 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('chitti', '0001_initial'),
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_auctions', to='members.member'),
        ),
        migrations.AddField(
            model_name='chittigroup',
            name='collector',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'collector'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_chitti_groups', to='accounts.staffprofile'),
        ),
        migrations.AddField(
            model_name='chittigroup',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_chitti_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auction',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auctions', to='chitti.chittigroup'),
        ),
        migrations.AddField(
            model_name='chittimember',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chitti_members', to='chitti.chittigroup'),
        ),
        migrations.AddField(
            model_name='chittimember',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chitti_memberships', to='members.member'),
        ),
        migrations.AlterUniqueTogether(
            name='auction',
            unique_together={('group', 'month_no')},
        ),
        migrations.AlterUniqueTogether(
            name='chittimember',
            unique_together={('group', 'token_no')},
        ),
    ]
