# Generated by Django 5.2.9 on 2026-01-17 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chitti', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auction',
            options={'ordering': ['month_no'], 'verbose_name': 'Auction', 'verbose_name_plural': 'Auctions'},
        ),
        migrations.AlterModelOptions(
            name='chittigroup',
            options={'ordering': ['start_date'], 'verbose_name': 'Chitti Group', 'verbose_name_plural': 'Chitti Groups'},
        ),
        migrations.AlterModelOptions(
            name='chittimember',
            options={'ordering': ['token_no'], 'verbose_name': 'Chitti Member', 'verbose_name_plural': 'Chitti Members'},
        ),
        migrations.AddField(
            model_name='chittigroup',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='chittigroup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
