# Generated by Django 5.2.9 on 2026-01-17 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chitti', '0003_alter_auction_options_alter_chittigroup_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chittigroup',
            options={},
        ),
        migrations.AlterField(
            model_name='chittigroup',
            name='code',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
    ]
