# Generated by Django 5.2.9 on 2026-01-19 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chitti', '0005_memberpayment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auction',
            options={'ordering': ['month_no']},
        ),
        migrations.AlterModelOptions(
            name='chittimember',
            options={'ordering': ['token_no']},
        ),
        migrations.AddField(
            model_name='chittigroup',
            name='parent_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_groups', to='chitti.chittigroup'),
        ),
    ]
