# Generated by Django 5.2.9 on 2026-01-23 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chitti', '0006_alter_auction_options_alter_chittimember_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_auctions', to='chitti.chittimember'),
        ),
    ]
