app = "smartkuri"

[http_service]
  internal_port = 8000
  force_https = true
  auto_start_machines = true
  auto_stop_machines = "stop"   
  min_machines_running = 0      

[deploy]
  release_command = "python manage.py migrate --noinput"

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1