# Generated by Django 5.2.9 on 2026-01-10 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_staffprofile_created_at'),
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemnotification',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='systemnotification',
            name='target_admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.staffprofile'),
        ),
    ]
