# Generated by Django 5.2.9 on 2026-01-03 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('role', models.CharField(choices=[('group_admin', 'Group Admin'), ('admin', 'Admin'), ('collector', 'Cash Collector'), ('member', 'Member')], max_length=20)),
            ],
        ),
    ]
