# Generated by Django 5.2.9 on 2026-01-10 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='is_subscribed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='subscription_end',
            field=models.DateField(blank=True, null=True),
        ),
    ]
