# Generated by Django 5.2.9 on 2026-01-10 07:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_staffprofile_is_blocked_staffprofile_is_subscribed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
