# Generated by Django 5.2.9 on 2026-01-24 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_subscriptionplan_max_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupsubscription',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='groupsubscription',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
