# Generated by Django 5.2.9 on 2026-01-24 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_alter_groupsubscription_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupsubscription',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='groupsubscription',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
