# Generated by Django 5.2.9 on 2026-01-08 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_first_login',
            field=models.BooleanField(default=True),
        ),
    ]
