# Generated by Django 5.2.9 on 2026-01-19 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_is_first_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='monthly_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='member',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('left', 'Left'), ('defaulted', 'Defaulted')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='member',
            name='total_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
