# Generated by Django 5.2.9 on 2026-01-20 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chitti', '0006_alter_auction_options_alter_chittimember_options_and_more'),
        ('members', '0003_member_monthly_amount_member_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='assigned_chitti_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='chitti.chittigroup'),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
