# Generated by Django 5.2.9 on 2026-01-24 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_member_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('left', 'Left'), ('defaulted', 'Defaulted'), ('completed', 'Completed')], default='active', max_length=20),
        ),
    ]
